
Databases:
  AMI:
    - /content/diarization_imp/data/ami_mini/audio/{uri}.wav

Protocols:
  AMI:
    SpeakerDiarization:
      mini:
        train:
          uri: /content/diarization_imp/data/ami_mini/lists/train.txt
          annotation: /content/diarization_imp/data/ami_mini/annotations/{uri}.rttm
        development:
          uri: /content/diarization_imp/data/ami_mini/lists/dev.txt
          annotation: /content/diarization_imp/data/ami_mini/annotations/{uri}.rttm
        test:
          uri: /content/diarization_imp/data/ami_mini/lists/test.txt
          annotation: /content/diarization_imp/data/ami_mini/annotations/{uri}.rttm
